
package com.ulht.cd.project.rmi.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Thu Jan 14 12:56:47 GMT 2021
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "printDate", namespace = "http://rmi.project.cd.ulht.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "printDate", namespace = "http://rmi.project.cd.ulht.com/")

public class PrintDate {


}

