
package com.ulht.cd.project.rmi.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Thu Jan 14 13:45:45 GMT 2021
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "printDateResponse", namespace = "http://rmi.project.cd.ulht.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "printDateResponse", namespace = "http://rmi.project.cd.ulht.com/")

public class PrintDateResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

